drop database chat;
CREATE DATABASE chat;

USE chat;

CREATE TABLE users (
  ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  USERNAME VARCHAR(20) NOT NULL,
  PASSWORD CHAR(32),

  UNIQUE(USERNAME)

);

CREATE TABLE rooms (
  ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ROOMNAME VARCHAR(20) NOT NULL,
  CREATOR INT NOT NULL,

  FOREIGN KEY (CREATOR)
    REFERENCES users(ID)
);

CREATE TABLE messages (
  ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  USERID INT NOT NULL,
  ROOMID INT NOT NULL,
  MESSAGE varchar(220) NOT NULL,

  FOREIGN KEY (USERID)
    REFERENCES users(ID),
  FOREIGN KEY (ROOMID)
    REFERENCES rooms(ID)
);

insert into users (username,password) values ('will','pwd');
insert into rooms (ROOMNAME,creator) values ('Hello',1);

/* Create other tables and define schemas for them here! */




/*  Execute this file from the command line by typing:
 *    mysql -u root < server/schema.sql
 *  to create the database and the tables.*/

