-- drop database chat;
CREATE DATABASE chat;

USE chat;

CREATE TABLE users (
  ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  USER_NAME VARCHAR(20) NOT NULL,
  PASSWORD CHAR(32)
);

CREATE TABLE rooms (
  ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ROOM_NAME VARCHAR(20) NOT NULL,
  CREATOR INT NOT NULL,

  FOREIGN KEY (CREATOR)
    REFERENCES users(ID)
);

CREATE TABLE messages (
  ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  USER_ID INT NOT NULL,
  ROOM_ID INT NOT NULL,
  MESSAGE varchar(220) NOT NULL,

  FOREIGN KEY (USER_ID)
    REFERENCES users(ID),
  FOREIGN KEY (ROOM_ID)
    REFERENCES rooms(ID)
);


/* Create other tables and define schemas for them here! */




/*  Execute this file from the command line by typing:
 *    mysql -u root < server/schema.sql
 *  to create the database and the tables.*/

